// The core engine block that burns lava
public static final BlockEntry<DieselEngineBlock> DIESEL_ENGINE = REGISTRATE
    .block("diesel_engine", DieselEngineBlock::new).register();

// The addable expansion blocks
public static final BlockEntry<Block> CYLINDER_BLOCK = REGISTRATE
    .block("cylinder_block", Block::new).register();

// Translates mechanical force to electrical power
public static final BlockEntry<Block> GENERATOR_BLOCK = REGISTRATE
    .block("generator_block", Block::new).register();

// Transmits electricity to the wheels
public static final BlockEntry<Block> TRACTION_MOTOR = REGISTRATE
    .block("traction_motor", Block::new).register();

//next section

package myaddon.content.transportation.behaviour;

import com.simibubi.create.content.contraptions.behaviour.MovementBehaviour;
import com.simibubi.create.content.contraptions.behaviour.MovementContext;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import java.util.HashSet;
import java.util.Set;

public class DieselPowertrainBehaviour extends MovementBehaviour {

    @Override
    public void tick(MovementContext context) {
        super.tick(context);
        if (context.world.isClientSide) return;

        // 1. Scan for touching Cylinder Blocks to calculate potential top speed
        int cylinderCount = countAttachedCylinders(context, context.localPos);

        // 2. Trace the physical powertrain connection loop
        boolean isPowertrainValid = verifyPowertrainGrid(context);

        // 3. Save the results to the train NBT tags for your Train Speed Mixin to read
        context.tileData.putBoolean("PowertrainActive", isPowertrainValid);
        context.tileData.putInt("CylinderCount", isPowertrainValid ? cylinderCount : 0);
    }

    private int countAttachedCylinders(MovementContext context, BlockPos enginePos) {
        int count = 0;
        // Check all 6 sides of the engine block for cylinders
        for (Direction dir : Direction.values()) {
            BlockState adjState = context.contraption.getBlocks().get(enginePos.relative(dir));
            if (adjState != null && adjState.is(ModBlocks.CYLINDER_BLOCK.get())) {
                count++;
            }
        }
        return count;
    }

    private boolean verifyPowertrainGrid(MovementContext context) {
        BlockPos enginePos = context.localPos;
        BlockPos generatorPos = null;
        BlockPos motorPos = null;

        // Step A: Find a vanilla Chain Block connected to the engine, and follow it to the Generator
        for (Direction dir : Direction.values()) {
            BlockPos currentCheck = enginePos.relative(dir);
            BlockState state = context.contraption.getBlocks().get(currentCheck);
            
            // Follow a line of chains if the player made a long drive shaft connection
            while (state != null && state.is(Blocks.CHAIN)) {
                currentCheck = currentCheck.relative(dir);
                state = context.contraption.getBlocks().get(currentCheck);
            }
            
            if (state != null && state.is(ModBlocks.GENERATOR_BLOCK.get())) {
                generatorPos = currentCheck;
                break;
            }
        }

        if (generatorPos == null) return false; // Fail: No chain linked to a Generator

        // Step B: Find a Wire connected to the Generator, and follow it to the Traction Motor
        for (Direction dir : Direction.values()) {
            BlockPos currentCheck = generatorPos.relative(dir);
            BlockState state = context.contraption.getBlocks().get(currentCheck);

            while (state != null && state.is(ModBlocks.WIRE_BLOCK.get())) {
                currentCheck = currentCheck.relative(dir);
                state = context.contraption.getBlocks().get(currentCheck);
            }

            if (state != null && state.is(ModBlocks.TRACTION_MOTOR.get())) {
                motorPos = currentCheck;
                break;
            }
        }

        // Return true if we successfully completed the circuit loop down to the motor
        return motorPos != null;
    }
}

//next section

// Inside your Train Mixin class that intercepts Create's train movement mechanics
@Inject(method = "maxSpeed", at = @At("RETURN"), cancellable = true)
private void applyDieselElectricSpeedBoost(CallbackInfoReturnable<Float> cir) {
    Train self = (Train) (Object) this;
    
    // Check our NBT storage data generated by the engine's MovementBehaviour
    boolean active = self.carriages.get(0).storageData.getBoolean("PowertrainActive");
    
    if (active) {
        int cylinders = self.carriages.get(0).storageData.getInt("CylinderCount");
        
        // Grab Create's base config train speed (usually around 0.4 or 0.5)
        float defaultMaxSpeed = cir.getReturnValue();
        
        // Add 0.2 blocks/tick per cylinder to the top speed value!
        float modifiedTopSpeed = defaultMaxSpeed + (cylinders * 0.2f);
        
        cir.setReturnValue(modifiedTopSpeed);
    }
}

//next section

